In [5]:
import numpy as np

In [52]:
from sklearn.datasets import load_iris

In [53]:
iris=load_iris()

In [56]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [57]:
X=iris.data

In [59]:
Y=iris.target

In [61]:
from keras.utils import to_categorical

In [62]:
Y=to_categorical(Y)

In [66]:
from sklearn.model_selection import train_test_split

In [67]:
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.33,random_state=42)

In [64]:
from sklearn.preprocessing import MinMaxScaler

In [65]:
scaler_obj=MinMaxScaler()

In [68]:
scaler_obj.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [70]:
scaled_X_train=scaler_obj.transform(X_train)
scaled_X_test=scaler_obj.transform(X_test)

In [72]:
from keras.models import Sequential
from keras.layers import Dense

In [85]:
model=Sequential()
model.add(Dense(10,input_dim=4,activation="relu"))
model.add(Dense(8,activation="relu"))
model.add(Dense(3,activation="softmax"))
model.compile(optimizer="adam",loss="categorical_crossentropy",metrics=['accuracy'])

In [86]:
model.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_13 (Dense)             (None, 10)                50        
_________________________________________________________________
dense_14 (Dense)             (None, 8)                 88        
_________________________________________________________________
dense_15 (Dense)             (None, 3)                 27        
Total params: 165
Trainable params: 165
Non-trainable params: 0
_________________________________________________________________


In [87]:
model.fit(scaled_X_train,y_train,epochs=150,verbose=2)

Epoch 1/150
 - 4s - loss: 1.0764 - accuracy: 0.3400
Epoch 2/150
 - 0s - loss: 1.0685 - accuracy: 0.3400
Epoch 3/150
 - 0s - loss: 1.0616 - accuracy: 0.3400
Epoch 4/150
 - 0s - loss: 1.0555 - accuracy: 0.3400
Epoch 5/150
 - 0s - loss: 1.0491 - accuracy: 0.3500
Epoch 6/150
 - 0s - loss: 1.0433 - accuracy: 0.3500
Epoch 7/150
 - 0s - loss: 1.0376 - accuracy: 0.3900
Epoch 8/150
 - 0s - loss: 1.0327 - accuracy: 0.5400
Epoch 9/150
 - 0s - loss: 1.0277 - accuracy: 0.5700
Epoch 10/150
 - 0s - loss: 1.0228 - accuracy: 0.6100
Epoch 11/150
 - 0s - loss: 1.0174 - accuracy: 0.6200
Epoch 12/150
 - 0s - loss: 1.0119 - accuracy: 0.6200
Epoch 13/150
 - 0s - loss: 1.0061 - accuracy: 0.6200
Epoch 14/150
 - 0s - loss: 0.9998 - accuracy: 0.6400
Epoch 15/150
 - 0s - loss: 0.9930 - accuracy: 0.6500
Epoch 16/150
 - 0s - loss: 0.9855 - accuracy: 0.6500
Epoch 17/150
 - 0s - loss: 0.9778 - accuracy: 0.6500
Epoch 18/150
 - 0s - loss: 0.9698 - accuracy: 0.6500
Epoch 19/150
 - 0s - loss: 0.9611 - accuracy: 0.6500
Ep

In [93]:
y_pred=model.predict_classes(scalled_x_test)

In [94]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [95]:
y=y_test.argmax(axis=1)

In [97]:
print("accuracy",accuracy_score(y,y_pred),"\n")
print(confusion_matrix(y,y_pred))
print(classification_report(y,y_pred))

accuracy 0.96 

[[19  0  0]
 [ 0 13  2]
 [ 0  0 16]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.87      0.93        15
           2       0.89      1.00      0.94        16

   micro avg       0.96      0.96      0.96        50
   macro avg       0.96      0.96      0.96        50
weighted avg       0.96      0.96      0.96        50



In [98]:
model.save('myfirstmodel.h5')

In [100]:
from keras.models import load_model
newmodel = load_model('myfirstmodel.h5')
newmodel.predict_classes(scalled_x_test)

array([1, 0, 2, 1, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])